apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-app
  template:
    metadata:
      labels:
        app: playground-app
        admission.datadoghq.com/cws-instrumentation.enabled: "true"
    spec:
      containers:
        - name: playground-app
          image: ghcr.io/loresuso/playground2:latest
          imagePullPolicy: Always
          env:
            - name: DD_SERVICE
              value: "playground-app"
            - name: DD_ENV
              value: "playground-env"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_TRACE_DEBUG
              value: "true"
            - name: DD_CLUSTER_NAME
              value: "playground-cluster"
            - name: DD_API_KEY
              value: "${dd_api_key}"
            - name: DD_SITE
              value: "${dd_site}"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "2"
