apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-app
  template:
    metadata:
      labels:
        app: playground-app
        admission.datadoghq.com/cws-instrumentation.enabled: "true"
    spec:
      containers:
        - name: playground-app
          image: docker.io/datadog/datadog-security-playground:latest
          imagePullPolicy: Always
          env:
            - name: DD_SERVICE
              value: "playground-app"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
