datadog:
  site: "datadoghq.com"
  apiKeyExistingSecret: "datadog-api-secret"
  
  apm:
    portEnabled: true
    port: 8126
    socketEnabled: true
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          ddTraceVersions:
            java: "1"
            python: "4"
            js: "5"
            php: "1"
            dotnet: "3"
            ruby: "2"
  
  env:
    - name: DD_HOSTNAME
      value: playground
    - name: DD_ENV
      value: "playground-env"
    - name: DD_CLUSTER_NAME
      value: "playground-cluster"
    - name: DD_KUBELET_TLS_VERIFY
      value: "false"
    - name: DD_SBOM_ENABLED
      value: "true"
    - name: DD_SBOM_CONTAINER_IMAGE_ENABLED
      value: "true"
    - name: DD_SBOM_CONTAINER_IMAGE_ALLOW_MISSING_REPODIGEST
      value: "true"
    - name: DD_RUNTIME_SECURITY_CONFIG_HASH_RESOLVER_REPLACE
      value: >-
        {
          "/app/malware.x64": "sha256:f3f7eb972a998047edb4c6e4287308236fcd8a9ef81dc13e6469590275af3cac",
          "/app/malware.arm64": "sha256:80bab7f4bc97e36724433f9ab2dffea7fc0bf0d0fd31a7b6a4012a4f0821737e"
        }
  securityAgent:
    runtime:
      enabled: true
  asm:
    threats:
      enabled: true

clusterAgent:
  enabled: true
  admissionController:
    cwsInstrumentation:
      enabled: true
      mode: remote_copy